version: "3.7"

services:
  server:
    image: lumosapi:latest
    networks:
      - host
    environment:
      BOOSTRAP_BOOT_TIMEOUT: 5s
      BOOSTRAP_SHUTDOWN_TIMEOUT: 10s
      APP_NAME: LUMOS-API
      PG_URL: ${PG_URL}
      PG_MAX_CONN: 10
      PG_MAX_CONN_IDLE_TIME: 1h
      LOG_LEVEL: info
      LOG_PRETTY: "false"
      HTTP_ADDR: 0.0.0.0:443
      HTTP_IDLE_TIMEOUT: 1m
      HTTP_PING_ROUTE: /ping
      HTTP_API_SERVE_PREFIX: /api
      HTTP_API_CORS_ALLOWED_HOSTS: "*"
      HTTP_STATIC_SERVE_PREFIX: /static/
      HTTP_HTML_SERVE_PREFIX: /
      HTTP_AUTO_CERT_ENABLED: "true"
      HTTP_AUTO_CERT_CACHE_DIR: /certificates
      HTTP_AUTO_CERT_HOSTS: api.lumos-care.ru
      HTTP_AUTO_CERT_EMAIL: skyksusha@gmail.com
      TG_BOT_TOKEN: ${TG_BOT_TOKEN}
      TG_BOT_ADMIN_CHAT_ID: ${TG_BOT_ADMIN_CHAT_ID}
      TG_BOT_POLLER_TIMEOUT: 30s
      TG_BOT_DEBUG: "false"
      UNISENDER_API_KEY: ${UNISENDER_API_KEY}
      HTTP_TRIAL_PAYMENTS_ROUTE_HASH: ${HTTP_TRIAL_PAYMENTS_ROUTE_HASH}
      HTTP_PRODAMUS_PAYMENT_NOTIFICATION_ROUTE_HASH: ${HTTP_PRODAMUS_PAYMENT_NOTIFICATION_ROUTE_HASH}
      HTTP_CLOUD_PAYMENTS_PAY_NOTIFICATION_ROUTE_HASH: ${HTTP_CLOUD_PAYMENTS_PAY_NOTIFICATION_ROUTE_HASH}
      HTTP_CLOUD_PAYMENTS_RECURRENT_NOTIFICATION_ROUTE_HASH: ${HTTP_CLOUD_PAYMENTS_RECURRENT_NOTIFICATION_ROUTE_HASH}
    ports:
      #      - target: 80
      #        published: 80
      #        protocol: tcp
      #        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - ssl-certs:/certificates
    deploy:
      restart_policy:
        condition: on-failure
      update_config:
        order: stop-first
      resources:
        limits:
          memory: 1024M
      mode: global
      placement:
        constraints:
          - node.hostname == cv4489663.novalocal

volumes:
  ssl-certs:
    external: true

networks:
  host:
    name: host
    external: true
