version: '3.7'

services:
  server:
    image: 127.0.0.1:5000/stackdemo
    build: .
    environment:
      BOOSTRAP_BOOT_TIMEOUT: 5s
      BOOSTRAP_SHUTDOWN_TIMEOUT: 10s
      APP_NAME: LUMOS-API
      PG_URL: ${PG_URL}
      PG_CONNECTION_TIMEOUT: 10s
      LOG_LEVEL: info
      LOG_PRETTY: 'false'
      HTTP_LISTEN_PORT: 80
      HTTP_LISTEN_HOST: '0.0.0.0'
      HTTP_IDLE_TIMEOUT: 1m
      HTTP_PING_ROUTE: /ping
      HTTP_API_SERVE_PREFIX: /api
      HTTP_STATIC_SERVE_PREFIX: /static/
      HTTP_HTML_SERVE_PREFIX: /
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - ssl-certs:/certificates
    deploy:
      restart_policy:
        condition: on-failure
      update_config:
        order: stop-first
      resources:
        limits:
          memory: 1024M
      mode: global
      placement:
        constraints:
          - node.hostname == cv4489663.novalocal

volumes:
  ssl-certs:
    external: true