version: '3.7'

services:
  #-----------------------------------------------------------------------------
  # Mathesar web service
  #
  # This service provides the main web server required to run Mathesar, using
  # our official Docker image hosted on Docker Hub
  #
  # As configured, this service exposes port 8000 to other services but not the
  # host system. This isolates it from being directly accessed  by the host
  # while allowing access via caddy.
  #
  service:
    container_name: mathesar_service
    image: mathesar/mathesar:latest
    networks:
      - host
    environment:
      SECRET_KEY: ${SECRET_KEY:?}

      # (Optional) Replace 'http://localhost' with custom domain(s) e.g.
      # 'yourdomain.com, 127.0.0.1' to manage the host(s) at which you want to
      # access Mathesar over http or https
      DOMAIN_NAME: ${DOMAIN_NAME:-http://localhost}

      # Edit the POSTGRES_* variables if you are not using the db service provided
      # below, or if you want to use a custom database user.

      # (Optional) Replace 'mathesar_django' with any custom name for the internal
      # database managed by mathesar web-service
      POSTGRES_DB: ${POSTGRES_DB:-mathesar_django}

      # (Optional) Replace 'mathesar' with any custom username for the
      # aforementioned database
      POSTGRES_USER: ${POSTGRES_USER:-mathesar}

      # (Optional) Replace 'mathesar' with any custom password for the
      # aforementioned database
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mathesar}

      # (Optional) Replace 'mathesar_db' with the name of the host running postgres
      POSTGRES_HOST: ${POSTGRES_HOST:-mathesar_db}

      # (Optional) Replace '5432' with the port on which postgres is running
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}

      DJANGO_SETTINGS_MODULE: config.settings.production

      # We set ALLOWED_HOSTS to * (allow all hosts) by default here since we are
      # relying on caddy to manage which domains could access the mathesar web
      # service.  If you do not want to use caddy add the domain(s) that you
      # want to ALLOWED_HOSTS. Doing so will restrict traffic from all other
      # domains.
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-*}

      # WARNING: MATHESAR_DATABASES is deprecated, and will be removed in a future release.
      MATHESAR_DATABASES: ${MATHESAR_DATABASES:-}
    volumes:
      - msar-static:/code/static
      - msar-media:/code/media
    healthcheck:
      test: curl -f http://localhost:8000
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 5s
    # If using caddy, expose the internal port 8000 only to other containers and
    # not the docker host.
    expose:
      - "8000"
    # Uncomment the following if not using caddy
    # ports:
    #   - ${HOST_PORT:-8000}:8000

  #-----------------------------------------------------------------------------
  # Caddy
  #
  # This service provides a reverse proxy for the Mathesar web server, using our
  # custom Caddy image hosted on Docker Hub. That image is customized to use a
  # Caddyfile with an appropriate configuration for Mathesar.
  #
  # Specifically, this service routes the requests to backend and the web
  # frontend of Mathesar while also serving essential staic files and user
  # uploaded datafiles(.csv/.tsv). It also provides SSL certificates
  # automatically for any custom domain(s) listed in DOMAIN_NAME that you might
  # want to use to access Mathesar.
  #
  # This service maps the default port for http(80) and https(443) of the host
  # system to that of docker's for allowing access to Mathesar over http or
  # https.
  #
  caddy-reverse-proxy:
    networks:
      - host
    image: mathesar/mathesar-caddy:latest
    # This service needs the config variables defined above.
    environment:
      SECRET_KEY: ${SECRET_KEY:?}

      # (Optional) Replace 'http://localhost' with custom domain(s) e.g.
      # 'yourdomain.com, 127.0.0.1' to manage the host(s) at which you want to
      # access Mathesar over http or https
      DOMAIN_NAME: ${DOMAIN_NAME:-http://localhost}

      # Edit the POSTGRES_* variables if you are not using the db service provided
      # below, or if you want to use a custom database user.

      # (Optional) Replace 'mathesar_django' with any custom name for the internal
      # database managed by mathesar web-service
      POSTGRES_DB: ${POSTGRES_DB:-mathesar_django}

      # (Optional) Replace 'mathesar' with any custom username for the
      # aforementioned database
      POSTGRES_USER: ${POSTGRES_USER:-mathesar}

      # (Optional) Replace 'mathesar' with any custom password for the
      # aforementioned database
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mathesar}

      # (Optional) Replace 'mathesar_db' with the name of the host running postgres
      POSTGRES_HOST: ${POSTGRES_HOST:-mathesar_db}

      # (Optional) Replace '5432' with the port on which postgres is running
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      # We set ALLOWED_HOSTS to * (allow all hosts) by default here since we are
      # relying on caddy to manage which domains could access the mathesar web
      # service.  If you do not want to use caddy add the domain(s) that you
      # want to ALLOWED_HOSTS. Doing so will restrict traffic from all other
      # domains.
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-*}
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
#      - "443:443"
    volumes:
      - msar-media:/code/media
      - msar-static:/code/static
      - msar-caddy:/data
      - /etc/hosts:/etc/hosts


volumes:
  msar-static:
    external: true
  msar-media:
    external: true
  msar-caddy:
    external: true


networks:
  host:
    name: host
    external: true